name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  data:
    path: ../data

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.24.0
